name: test_install

on:
  push:
    branches:
      - master
        
jobs:

  test_install:
    runs-on: macos-latest
    steps:

      - name: Add tap
        run: brew tap pc-magas/mkdotenv

      - name: install mkdotenv
        run: brew install pc-magas/mkdotenv/formula

      - name: testrun
        run: mkdotenv --help